# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

persona_show:
    path: /persona/{id}
    controller: App\Controller\PersonaController::show

persona_new:
    path: /persona/new
    controller: App\Controller\PersonaController::new

persona_index:
    path: /persona
    controller: App\Controller\PersonaController::index

solicitud_show:
    path: /solicitud/{id}
    controller: App\Controller\SolicitudController::show

merito_add:
    path: /merito/add
    controller: App\Controller\MeritoController::add

merito_save:
    path: /merito/save
    controller: App\Controller\MeritoController::save
    methods: [POST]

merito_edit:
    path: /merito/edit/{id}
    controller: App\Controller\MeritoController::edit

merito_edit_data:
    path: /merito/{id}/edit
    controller: App\Controller\MeritoController::getEditData
    methods: [GET]

merito_delete:
    path: /merito/delete/{id}
    controller: App\Controller\MeritoController::delete
    methods: [POST]
