# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

persona_show:
    path: /persona/{id}
    controller: App\Controller\PersonaController::show

persona_index:
    path: /personas
    controller: App\Controller\PersonaController::index

quinquenio_solicitud_show:
    path: /solicitud/{id}
    controller: App\Controller\QuinquenioSolicitudController::show

quinquenio_merito_add:
    path: /merito/add
    controller: App\Controller\QuinquenioMeritoController::add

merito_add:
    path: /merito/add
    controller: App\Controller\QuinquenioMeritoController::add